---
- import_tasks: root-configuration.yml
  tags:
    - root
  become: true
- import_tasks: python.yml
  name: build python
  tags:
    - python
  become: true
- import_tasks: vim.yml
  name: build vim
  tags:
    - vim
  become: true
- import_tasks: git.yml
  name: install latest git
  tags:
    - git
  become: true
