---
- name: install system packages
  package:
    state: latest
    name:
      - ctags
      - jq
      - direnv
      - make
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
      - git
      - libselinux-python
      - nginx
      - python3-devel
      - redhat-rpm-config
      - tmux
      - bzip2
      - bzip2-devel
      - wget
      - zlib-devel
      - gzip
  when: ansible_distribution == 'Fedora'
- name: install system packages
  package:
      name:
        - build-essential
        - jq
        - ctags
        - direnv
        - git
        - libreadline-dev
        - libsqlite3-dev
        - nginx
        - python-dev
        - python3-dev
        - cmake
        - tmux
      state: latest
      update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: put selinux in permissive mode
  selinux: policy=targeted state=permissive
  when: ansible_distribution == 'Fedora'
- name: Ensure wheel group present
  group:
    name: wheel
    state: present
- name: ensure wheel group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
- name: add privileged user
  user:
    name: "{{ username }}"
    groups:
      - "wheel"
- name: add authorized_keys for target_user
  authorized_key:
    key: "{{ keys }}"
    user: "{{ username }}"
