---
- name: put selinux in permissive mode
  selinux: policy=targeted state=permissive
  when: ansible_distribution == 'Fedora'
- name: install system packages
  package: name={{ item }} state=present
  with_items:
    - ctags
    - jq
    - direnv
    - gcc
    - git
    - nginx
    - python3-devel
    - redhat-rpm-config
    - tmux
  when: ansible_distribution == 'Fedora'
- name: install system packages
  apt: 
      name: "{{ item }}"
      state: present 
      update_cache: yes
  with_items:
    - build-essential
    - jq
    - ctags
    - direnv
    - git
    - libreadline-dev
    - libsqlite3-dev
    - nginx
    - python-dev
    - python3-dev
    - cmake
    - tmux
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Ensure wheel group present
  group:
    name: wheel
    state: present
- name: ensure wheel group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
- name: add privelaged user
  user:
    name: "{{ username }}"
    groups:
      - "wheel"
- name: add authorized_keys for target_user
  authorized_key:
    key: "{{ keys }}"
    user: "{{ username }}"
