---
- name: install selinux tools
  package:
    state: latest
    name:
      - libselinux
      - policycoreutils-python-utils
- name: put selinux in permissive mode
  selinux: policy=targeted state=permissive
