---
- name: install build dependencies
  apt:
    name:
      - libncurses5-dev
      - libgnome2-dev
      - libgnomeui-dev
      - libgtk2.0-dev
      - libatk1.0-dev
      - libbonoboui2-dev
      - libcairo2-dev
      - libx11-dev
      - libxpm-dev
      - libxt-dev
      - python-dev
      - python3-dev
      - git
  tags:
    - build
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: install build dependencies
  apt:
    name:
      - ctags
      - git
      - python
      - python-devel
      - python3
      - python3-devel
      - tcl-devel
  tags:
    - build
  when: ansible_distribution == 'Fedora'
- name: remove vim
  package:
    name:
      - vim
      - vim-runtime
      - gvim
      - vim-tiny
      - vim-common
      - vim-gui-common
      - vim-nox
    state: absent
  tags:
    - remove
- name: clone vim
  git:
    dest: /tmp/vim
    repo: https://github.com/vim/vim
  tags:
    - install
- name: configure vim
  command:
    argv:
      - ./configure
      - --with-features=huge
      - --enable-multibyte
      - --enable-python3interp=yes
      - --with-python3-command=/usr/local/bin/python3.6
      - --with-python3-config-dir=$(python3.6m-config --configdir)
      - --enable-cscope
      - --prefix=/usr/local
    chdir: /tmp/vim
  tags:
    - install
- name: make
  command:
    chdir: /tmp/vim
    cmd: make VIMRUNTIMEDIR=/usr/local/share/vim/vim82
  tags:
    - install
- name: make install
  command:
    chdir: /tmp/vim
    cmd: make install
  tags:
    - install
