---
- name: bootstrap ansible
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install packages for ansible
      package:
        name: python-minimal
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      changed_when: false
    - name: install packages for ansible
      package:
        name: python3-dnf
        state: latest
      when: ansible_distribution == 'Fedora'
      changed_when: false

- name: configure servers
  hosts: sandbox
  roles:
    - general

- name: set up kafka
  hosts: kafka
  roles:
    - general
    - kafka
