---
- name: bootstrap ansible
  hosts: all
  tasks:
    - set_fact:
        timestamp: '{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}'
- name: configure servers
  hosts: sandbox
  roles:
    - root
    - user
    - security
- name: set up kafka
  hosts: kafka
  vars:
    kafka_url: "http://apache-mirror.8birdsvideo.com/kafka/2.4.0/kafka_2.12-2.4.0.tgz"
  roles:
    - root
    - user
    - security
    - kafka
- name: set up vagrant
  hosts: vagrant
  vars:
    username: vagrant
    email: sahmed@resy.com
  roles:
    - root
    - user
