---
- name: bootstrap ansible
  hosts: all
  vars:
    python_versions:
      - 3.5.7
      - 3.6.10
      - 3.7.6
    username: salah
    keys: "https://github.com/salah93.keys"
    full_name: Salah Ahmed
    email: salahs.email@pm.me
  tasks:
    - set_fact:
        timestamp: '{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}'
- name: configure servers
  hosts: sandbox
  roles:
    - root
    - user
    - security
- name: set up kafka
  hosts: kafka
  vars:
    kafka_url: "http://apache-mirror.8birdsvideo.com/kafka/2.4.0/kafka_2.12-2.4.0.tgz"
  roles:
    - root
    - user
    - security
    - kafka
- name: set up vagrant
  hosts: vagrant
  vars:
    username: vagrant
    email: sahmed@resy.com
  roles:
    - root
    - user
- name: set up web app
  hosts: web
  vars_files:
    - vars/web_vault.yml
  vars:
    appname: salahs_website
    private_gpg_key: "{{ vault_private_gpg_key }}"
    private_deploy_key: "{{ vault_private_deploy_key }}"
    app_repo_link: git@github.com:salah93/website
  roles:
    - root
    - user
    - security
    - web
