---
- name: bootstrap ansible
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install python for ansible
      package:
        name: python-minimal
        state: latest
      ignore_errors: yes
      changed_when: false
    - name: install packages for ansible
      package:
        name: python3-dnf
        state: latest
      ignore_errors: yes
      changed_when: false
- name: configure servers
  hosts: sandbox
  roles:
    - general
- name: set up kafka
  hosts: kafka
  roles:
    - general
    - kafka
