---
- name: bootstrap ansible
  hosts: all
  gather_facts: no
  tasks:
    - name: update dnf
      dnf:
        state: latest
        name: "*"
    - name: install python for ansible
      dnf:
        name:
          - python-dnf
- name: configure sandbox
  hosts: sandbox
  roles:
    - root
    - security
    - user
- name: set up kafka
  hosts: kafka
  roles:
    - root
    - security
    - user
    - kafka
- name: set up vagrant
  hosts: vagrant
  roles:
    - root
    - user
- name: set up web app
  hosts: web
  vars_files:
    - vars/web_vault.yml
  roles:
    - root
    - security
    - user
    - web
