---
- hosts: new_server
  user: root
  vars:
    github_user: salah93
    username: goku
    email: salah.ahmed.hslc@gmail.com
    email_password: "{{ lookup('env','GMAIL_PW') }}"
    ssh_port: 22
  roles:
    - setup
    - ssh
    - firewall
    - fail2ban
    - user
