---
- name: configure sandbox
  hosts: resy
  vars:
    username: sahmed
    email: sahmed@resy.com
  tasks:
    - set_fact:
        timestamp: '{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}'
  roles:
    - user
