---
- name: Ensure wheel group present
  group:
    name: wheel
    state: present

- name: ensure wheel group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: create user
  user:
    name: "{{ username }}"
    groups: wheel

- name: add authorized key
  authorized_key:
    user: "{{ username }}"
    key: https://github.com/"{{ github_user }}".keys

- name: add directories
  become: "{{ username }}"
  file:
    path: "~/{{ item }}"
    state: directory
    mode: 0755 
  with_items:
    - Projects
    - Experiments
    - .virtualenvs
    - .vim/bundle


- name: clone scripts directory
  become: "{{ username }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    with_items:
      - { repo: "git@github.com:salah93/scripts.git", dest: "~/Projects"}
      - { repo: "git@github.com:VundleVim/Vundle.vim.git", dest: "~/.vim/bundle/"}

- name: link config files to script files
  become: "{{ username }}"
  file: 
    src: "~/Projects/scripts/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: yes
    with_items:
      - bashrc
      - bash_profile
      - vimrc
      - gitconfig

- name: install python packages
  become: "{{ username }}"
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "~/.virtualenvs/env"
    with_items:
      - requests
      - ipython
      - crosscompute
