---
- name: add directories
  file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "Experiments"
    - "Projects"
    - ".virtualenvs"
    - ".vim/bundle"

- name: install python packages
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "$HOME/.virtualenvs/env"
  with_items:
    - requests
    - ipython
