---
- name: add directories
  file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "Experiments"
    - "Projects"
    - ".virtualenvs"
    - ".vim/bundle"
- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
  become: yes
  become_user: root
  tags:
    - pip
- name: install python packages
  pip:
    name: ['ipython']
    state: latest
    virtualenv: "$HOME/.virtualenvs/env"
  tags:
    - pip
- name: configure git email
  git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
- name: configure git name
  git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"
- name: clone scripts
  git:
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    repo: "https://github.com/{{ item.repo }}"
  with_items:
    - {"repo": "VundleVim/Vundle.vim",
       "dest": "~/.vim/bundle/Vundle.vim"}
    - {"repo": "salah93/dotfiles",
       "dest": "~/Projects/dotfiles"}
    - {"repo": "salah93/cltools",
       "dest": "~/Projects/scripts"}
- name: link rc files
  file:
    force: yes
    path: "{{ item.dest }}"
    state: link
    src: "{{ item.src}}"
  with_items:
    - {"src": "~/Projects/dotfiles/bashrc",
       "dest": "~/.bashrc"}
    - {"src": "~/Projects/dotfiles/bash_profile",
       "dest": "~/.bash_profile"}
    - {"src": "~/Projects/dotfiles/vimrc",
       "dest": "~/.vimrc"}
    - {"src": "~/Projects/dotfiles/tmux.conf",
       "dest": "~/.tmux.conf"}
    - {"src": "~/Projects/scripts",
       "dest": "~/.scripts"}
