---
- name: add directories
  file:
    path: "$HOME/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - "Experiments"
    - "Projects"
    - ".virtualenvs"
    - ".vim/bundle"
- name: configure git email
  git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
- name: configure git name
  git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"
- name: clone scripts
  git:
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    repo: "https://github.com/{{ item.repo }}"
  with_items:
    - {"repo": "VundleVim/Vundle.vim",
       "dest": "$HOME/.vim/bundle/Vundle.vim"}
    - {"repo": "salah93/dotfiles",
       "dest": "$HOME/Projects/dotfiles"}
    - {"repo": "salah93/cltools",
       "dest": "$HOME/Projects/scripts"}
- name: link rc files
  file:
    force: yes
    path: "{{ item.dest }}"
    state: link
    src: "{{ item.src}}"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - {"src": "$HOME/Projects/dotfiles/bashrc",
       "dest": "$HOME/.bashrc"}
    - {"src": "$HOME/Projects/dotfiles/bash_profile",
       "dest": "$HOME/.bash_profile"}
    - {"src": "$HOME/Projects/dotfiles/vimrc",
       "dest": "$HOME/.vimrc"}
    - {"src": "$HOME/Projects/dotfiles/tmux.conf",
       "dest": "$HOME/.tmux.conf"}
    - {"src": "$HOME/Projects/scripts",
       "dest": "$HOME/.scripts"}
- name: Install vim plugins
  command: vim +PluginInstall +qall
- name: Install vim plugins
  command:
    cmd: python3 install.py --all
    chdir: $HOME/.vim/bundle/YouCompleteMe
