---
- name: add directories
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "Experiments"
    - "Projects"
    - ".virtualenvs"
    - ".vim/bundle"
- name: configure git email
  git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
- name: configure git name
  git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"
- name: clone scripts
  git:
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    repo: "https://github.com/{{ item.repo }}"
  with_items:
    - {"repo": "VundleVim/Vundle.vim",
       "dest": "/home/{{ username }}/.vim/bundle/Vundle.vim"}
    - {"repo": "salah93/dotfiles",
       "dest": "/home/{{ username }}/Projects/dotfiles"}
    - {"repo": "salah93/cltools",
       "dest": "/home/{{ username }}/Projects/scripts"}
- name: link rc files
  file:
    force: yes
    path: "{{ item.dest }}"
    state: link
    src: "{{ item.src}}"
  with_items:
    - {"src": "/home/{{ username }}/Projects/dotfiles/bashrc",
       "dest": "/home/{{ username }}/.bashrc"}
    - {"src": "/home/{{ username }}/Projects/dotfiles/bash_profile",
       "dest": "/home/{{ username }}/.bash_profile"}
    - {"src": "/home/{{ username }}/Projects/dotfiles/vimrc",
       "dest": "/home/{{ username }}/.vimrc"}
    - {"src": "/home/{{ username }}/Projects/dotfiles/tmux.conf",
       "dest": "/home/{{ username }}/.tmux.conf"}
    - {"src": "/home/{{ username }}/Projects/scripts",
       "dest": "/home/{{ username }}/.scripts"}
