---
- name: open websocket port
  firewalld:
    port: "{{ websocket_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  become: true
- name: load single-run scripts
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  become: true
  loop: "{{ single_services }}"
- name: load multi-run scripts 1
  service:
    name: "{{ item }}@1"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 2
  service:
    name: "{{ item }}@2"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 3
  service:
    name: "{{ item }}@3"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 4
  service:
    name: "{{ item }}@4"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 5
  service:
    name: "{{ item }}@5"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 6
  service:
    name: "{{ item }}@6"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 7
  service:
    name: "{{ item }}@7"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 8
  service:
    name: "{{ item }}@8"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 9
  service:
    name: "{{ item }}@9"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 10
  service:
    name: "{{ item }}@10"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 11
  service:
    name: "{{ item }}@11"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 12
  service:
    name: "{{ item }}@12"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 13
  service:
    name: "{{ item }}@13"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 14
  service:
    name: "{{ item }}@14"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 15
  service:
    name: "{{ item }}@15"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 16
  service:
    name: "{{ item }}@16"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 17
  service:
    name: "{{ item }}@17"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 18
  service:
    name: "{{ item }}@18"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 19
  service:
    name: "{{ item }}@19"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: load multi-run scripts 20
  service:
    name: "{{ item }}@20"
    state: restarted
    enabled: true
  become: true
  loop: "{{ multi_services }}"
- name: delete deploy key
  file:
    state: absent
    path: "{{ deploy_key_path }}"
  become: true
- name: delete private key
  file:
    state: absent
    path: "{{ gpg_key_path }}"
  become: true
