---
- name: update vim
  dnf: 
    name: "vim-minimal"  
    state: latest

- name: download packages
  dnf: 
    name: "{{ item }}"  
  with_items:
    - vim
    - python-devel
    - git
    - tmux
    - redhat-rpm-config
    - gcc
    - libselinux-python

- name: install python packages
  easy_install: 
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - virtualenv

- name: Ensure wheel group present
  group:
    name: wheel
    state: present

- name: ensure wheel group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: add privelaged user
  user:
    name: "{{ target_user.user }}"
    groups: 
      - "wheel"

- name: add authorized_keys for target_user
  authorized_key:
    key: "{{ target_user.key }}"
    user: "{{ target_user.user }}"
