---
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present

- name: Disable password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: Change ssh port number
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Port "
    line: "Port {{ssh_port}}"
    state: present
