---
- name: add directories
  file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "Experiments"
    - "Projects"
    - ".virtualenvs"
    - ".vim/bundle"

- name: install python packages
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "$HOME/.virtualenvs/env"
  with_items:
    - ipython

- name: clone scripts
  git:
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    repo: "https://github.com/{{ item.repo }}"
  with_items:
    - {"repo": "VundleVim/Vundle.vim",
       "dest": "~/.vim/bundle/Vundle.vim"}
    - {"repo": "salah93/dotfiles",
       "dest": "~/Projects/"}

- name: install vim plugins
  command: /usr/bin/vim +PluginInstall +qal

- name: link rc files
  file:
    force: yes
    path: "{{ item.dest }}"
    state: link
    src: "{{ item.src}}"
  with_items:
    - {"src": "~/Projects/dotfiles/bashrc",
       "dest": "~/.bashrc"}
    - {"src": "~/Projects/dotfiles/bash_profile",
       "dest": "~/.bash_profile"}
    - {"src": "~/Projects/dotfiles/vimrc",
       "dest": "~/.vimrc"}
