---
- name: load uwsgi
  service:
    name: emperor.uwsgi.service
    state: restarted
  become: true
- name: load nginx
  service:
    name: nginx
    state: restarted
  become: true
- name: delete deploy key
  file:
    state: absent
    path: "$HOME/.deploy_key"
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
- name: delete private key
  file:
    state: absent
    path: "$HOME/.private_key"
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
- name: remove git secret repo
  file:
    state: absent
    path: /root/git-secret
  become: true
- name: open port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled
  become: true
