---
- name: enable nginx
  service:
    name: nginx
    state: restarted
  become: true
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
- name: enable emperor uwsgi
  service:
    name: emperor.uwsgi.service
    state: restarted
  become: true
- name: restart emperor uwsgi
  service:
    name: nginx
    state: restarted
  become: true
- name: delete deploy key
  file:
    state: absent
    path: "$HOME/.deploy_key"
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
- name: delete private key
  file:
    state: absent
    path: "$HOME/.private_key"
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
