---
- name: load uwsgi
  service:
    name: emperor.uwsgi.service
    state: restarted
    enabled: true
  become: true
- name: load nginx
  service:
    name: nginx
    state: restarted
    enabled: true
  become: true
- name: load consumers 1
  service:
    name: "{{ item }}@1"
    state: restarted
    enabled: true
  become: true
  loop: "{{ consumers }}"
- name: load consumers 2
  service:
    name: "{{ item }}@2"
    state: restarted
    enabled: true
  become: true
  loop: "{{ consumers }}"
- name: load consumers 3
  service:
    name: "{{ item }}@2"
    state: restarted
    enabled: true
  become: true
  loop: "{{ consumers }}"
- name: load consumers 4
  service:
    name: "{{ item }}@2"
    state: restarted
    enabled: true
  become: true
  loop: "{{ consumers }}"
- name: load consumers 5
  service:
    name: "{{ item }}@2"
    state: restarted
    enabled: true
  become: true
  loop: "{{ consumers }}"
- name: load consumers 6
  service:
    name: "{{ item }}@2"
    state: restarted
    enabled: true
  become: true
  loop: "{{ consumers }}"
- name: delete deploy key
  file:
    state: absent
    path: "{{ deploy_key_path }}"
  become: true
- name: delete private key
  file:
    state: absent
    path: "{{ gpg_key_path }}"
  become: true
- name: open port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled
  become: true
