#!/bin/bash
set -eu


printl() {
    echo ===================================================================
    echo                $@
    echo ===================================================================
}

printl provisioning
sleep 5

IPS=`terraform output -json ips | jq -r '. | join(",")'`,

cd $PLAYBOOK_DIR
ansible-playbook \
    --vault-password-file ./.ansible-secret \
    -u ${REMOTE_USER} \
    -i ${IPS} \
    sandbox-playbook.yml
