---
- name: download packages
  dnf: 
    name: "{{ item }}"
  with_items:
    - firewalld
    - python-firewall

- name: enable firewall
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open ssh port
  firewalld:
    port: "{{ ssh_port }}/tcp"
    state: enabled
    permanent: true
  notify: restart firewall
