#!/bin/bash
set -eu


printl() {
    echo ===================================================================
    echo                $@
    echo ===================================================================
}

IPS=`terraform output -json ips | jq -r '. | join(",")'`,
LOGSERVER=`terraform output logserver`
echo $IPS
echo $LOGSERVER

printl Provisioning...
cd $PLAYBOOK_DIR
sleep 5

ansible-playbook \
    --vault-password-file ./.ansible-secret \
    -u ${REMOTE_USER} \
    -e release=${NEW_RELEASE} \
    -e logserver=${LOGSERVER} \
    -i ${IPS} \
    ./web-playbook.yml
