#!/bin/bash
set -eu

IPS=`terraform output -json ips | jq -r '. | join(",")'`,

cd $PLAYBOOK_DIR
ansible-playbook \
    --vault-password-file ./.ansible-secret \
    -u ${REMOTE_USER} \
    -e release=${NEW_RELEASE} \
    -e logserver=${LOGSERVER} \
    -i ${IPS}, \
    --ssh-extra-args="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
    "web-playbook.yml"
