---
- name: logging block
  tags:
    - logging
  block:
    - name: update yum
      yum:
        name: "*"
        state: latest
    - name: install syslog-ng
      package:
        name: syslog-ng
        state: latest
    - name: Open port 514/udp
      firewalld:
        port: 514/udp
        permanent: yes
        immediate: yes
        state: enabled
    - name: Open port 514/tcp
      firewalld:
        port: 514/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
    - name: add syslog-ng config
      copy:
        src: files/syslog-ng.conf
        dest: /etc/syslog-ng/conf.d/app.conf
      notify:
        - enable syslog-ng
    - name: add logrotation for app
      copy:
        src: files/app-log-rotate
        dest: /etc/logrotate.d/app
