---
- name: logging block
  tags:
    - logging
  block:
    - name: update yum
      yum:
        name: "*"
        state: latest
    - name: install rsyslog
      yum:
        name: rsyslog
        state: latest
    - name: Open port 514/udp
      firewalld:
        port: 514/udp
        permanent: yes
        immediate: yes
        state: enabled
    - name: Open port 514/tcp
      firewalld:
        port: 514/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
    - name: update rsys config
      copy:
        src: files/rsyslog.conf
        dest: /etc/rsyslog.conf
      notify:
        - enable rsyslog
    - name: add logrotation for app
      copy:
        src: files/app-log-rotate
        dest: /etc/logrotate.d/app
