---
- name: install make
  package:
    name:
      - make
  tags:
    - install
- name: clone git-secret
  git:
    dest: "git-secret"
    repo: "https://github.com/sobolevn/git-secret.git"
- name: make build git-secret
  make:
    chdir: git-secret
    target: build
- name: make install git-secret
  make:
    chdir: git-secret
    target: install
  environment:
    PREFIX: /usr/local
