---
- name: install uwsgi python package
  pip:
    name: ['uwsgi']
    virtualenv: "/root/venvs/uwsgi"
    virtualenv_python: "python3.8"
    version: "2.0.18"
- name: add service user
  user:
    name: "{{ appname }}"
    system: yes
    create_home: yes
  become: true
- import_tasks: service_user.yml
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
- import_tasks: decrypt_secrets.yml
  become: true
- import_tasks: uwsgi.yml
  become: true
- import_tasks: nginx.yml
  become: true
- import_tasks: systemd.yml
  become: true
- name: (re)start services
  debug:
    msg: trigger
  changed_when: true
  notify:
    - load uwsgi
    - load nginx
