---
- import_tasks: selinux.yml
  become: true
- import_tasks: git_secret.yml
  become: true
- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: "pip3.8"
  become: true
- name: install uwsgi python package
  pip:
    name: ['uwsgi']
    virtualenv: "/root/venvs/uwsgi"
    virtualenv_python: "python3.8"
    version: "2.0.18"
- name: add service group
  group:
    name: "nginx-{{ appname }}"
- name: add service user
  user:
    name: "{{ appname }}"
    groups:
      - "nginx-{{ appname }}"
  become: true
- import_tasks: service_user.yml
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
- import_tasks: uwsgi.yml
  become: true
- import_tasks: nginx.yml
  become: true
- import_tasks: systemd.yml
  become: true
