---
- name: install nginx
  package:
    name:
      - nginx
  tags:
    - install
- name: add main nginx confg
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
- name: add appname nginx confg
  template:
    src: templates/app.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
    owner: root
    group: root
    mode: 0644
