---
- name: install uwsgi python package
  pip:
    name: ['uwsgi']
    virtualenv: "$HOME/.virtualenvs/uwsgi"
    virtualenv_python: "python3.6"
    executable: "pip3.6"
- name: clone app
  git:
    accept_hostkey: yes
    dest: "$HOME/{{ appname }}"
    repo: "{{ app_repo_link }}"
    version: master
- name: install app requirement packages
  pip:
    requirements: "$HOME/{{ appname }}/requirements.txt"
    virtualenv: "$HOME/.virtualenvs/{{ appname }}"
    virtualenv_python: "python3.6"
    executable: "pip3.6"
- name: install app requirement packages
  pip:
    name: "$HOME/{{ appname }}"
    editable: "yes"
    virtualenv: "$HOME/.virtualenvs/{{ appname }}"
    virtualenv_python: "python3.6"
    executable: "pip3.6"
- name: link files to /opt
  file:
    force: yes
    state: link
    path: "{{ item.dest }}"
    src: "{{ item.src}}"
  with_items:
    - {"src": "$HOME/{{ appname }}",
       "dest": "/opt/{{ appname }}"}
    - {"src": "$HOME/.virtualenvs",
       "dest": "/opt/venvs"}
