---
- name: add Emperor uwsgi ini file
  template:
    src: templates/emperor.uwsgi.ini.j2
    dest: /etc/uwsgi/emperor.uwsgi.ini
    owner: root
    group: root
    mode: 0644
- name: add uwsgi vassal
  template:
    src: "templates/app.uwsgi.ini.j2"
    dest: "/etc/uwsgi/vassals/{{ appname }}.uwsgi.ini"
    owner: root
    group: root
    mode: 0644
