---
- name: create uwsgi directory
  file:
    state: directory
    path: /etc/uwsgi/vassals
    mode: 0774
    owner: root
    group: root
- name: add Emperor uwsgi ini file
  template:
    src: templates/emperor.uwsgi.ini.j2
    dest: /etc/uwsgi/emperor.uwsgi.ini
    mode: 0644
    owner: root
    group: root
- name: add uwsgi vassal
  template:
    src: "templates/app.uwsgi.ini.j2"
    dest: "/etc/uwsgi/vassals/{{ appname }}.uwsgi.ini"
    mode: 0644
    owner: "{{ appname }}"
    group: "{{ appname }}"
- name: create uwsgi sockets directory
  file:
    state: directory
    path: "/run/{{ appname }}"
    mode: 0770
    owner: "{{ appname }}"
    group: "nginx"
