# download python2-dnf
- name: download packages
  become: true
  dnf: 
    name: "{{ item }}"  
    state: latest
  with_items:
    - vim-minimal
    - vim
    - python-setuptools
    - git
    - tmux
    - libselinux-python
  when: ansible_distribution == 'Fedora'

- name: download packages
  become: true
  apt: 
    name: "{{ item }}"  
  with_items:
    - git
    - vim-minimal
    - vim
    - python-setuptools
    - tmux
  when: ansible_distribution == 'Ubuntu'

- name: install pip
  become: true
  easy_install: 
    name: pip

- name: install python packages
  become: true
  pip:
    name: "{{ item }}"
    state: latest
    with_items:
      - pip
      - virtualenv
