---
- name: set private key paths
  set_fact:
    gpg_key_path: /tmp/.private
- name: add private key file
  template:
    src: templates/private_key.j2
    dest: "{{ gpg_key_path }}"
    owner: root
    group: root
    mode: 0400
  notify:
    - delete private key
- name: import private gpg key
  command:
    cmd: gpg2  --pinentry-mode=loopback --passphrase {{ private_gpg_key_pass }} --import {{ gpg_key_path }}
  become: true
- name: decrypt envrc file
  command:
    cmd: git-secret reveal -p {{ private_gpg_key_pass }}
    chdir: "/opt/{{ appname }}"
  become: true
  environment:
    SECRETS_GPG_COMMAND: gpg2
