---
- name: add service user
  user:
    name: "{{ appname }}"
    system: yes
    create_home: no
  become: true
- import_tasks: service_user.yml
  become: true
  become_user: "{{ appname }}"
  become_method: sudo
- import_tasks: decrypt_secrets.yml
  become: true
- import_tasks: systemd.yml
  become: true
- name: (re)start services
  debug:
    msg: trigger
  changed_when: true
  notify:
    - open websocket port
    - load single-run scripts
    - load multi-run scripts 1
    - load multi-run scripts 2
    - load multi-run scripts 3
    - load multi-run scripts 4
    - load multi-run scripts 5
    - load multi-run scripts 6
